---
booktitle: Proceedings of The 2021 Causal Analysis Workshop Series
shortname: CAWS
volume: '160'
year: '2021'
start: 2021-07-16
end: 2021-07-16
published: 2021-12-01
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: CAWS2021
month: 0
cycles: false
bibtex_editor: Ma, Sisi and Kummerfeld, Erich
editor:
- given: Sisi
  family: Ma
- given: Erich
  family: Kummerfeld
title: Proceedings of Machine Learning Research
description: |
  Proceedings of The 2021 Causal Analysis Workshop Series
    Held in Minneapolis, Minnesota, USA on 16 July 2021

  Published as Volume 160 by the Proceedings of Machine Learning Research on 01 December 2021.

  Volume Edited by:
    Sisi Ma
    Erich Kummerfeld

  Series Editors:
    Neil D. Lawrence
    * Mark Reid
date_str: 16 Jul
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v160"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v160
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v160
email: ''
conference:
  name: Causal Analysis Workshop Series
  url: https://cawsnetwork.com/caws2021cfp/
  location: Minneapolis, Minnesota, USA
  dates:
  - 2021-07-16
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v160/caws2021.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v160/caws2021.bib
